# Generated by Django 5.1.6 on 2025-02-11 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["title"], "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["title"]},
        ),
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
