# Generated by Django 5.1.6 on 2025-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_category_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="test_slug", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="test_title", max_length=255),
            preserve_default=False,
        ),
    ]
