# Generated by Django 5.1.6 on 2025-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_slug_post_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="posts",
        ),
    ]
