# Generated by Django 5.1.6 on 2025-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_post_comment_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(),
        ),
    ]
