# Generated by Django 5.1.6 on 2025-02-11 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_category_slug_alter_post_slug_alter_tag_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="posts",
            new_name="post",
        ),
    ]
