# Generated by Django 5.1.6 on 2025-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learnings',
            field=models.TextField(default='W tym kursie nauczysz się...'),
        ),
    ]
